# Makefile for the focaltech touchscreen drivers.


fts_tp-y	+=  focaltech_core.o
fts_tp-y	+=  focaltech_ex_fun.o
fts_tp-y	+=  focaltech_ex_mode.o
fts_tp-y	+=  focaltech_gesture.o
fts_tp-y	+=  focaltech_esdcheck.o
fts_tp-y   +=  focaltech_point_report_check.o


fts_tp-y	+=  focaltech_flash.o



fts_tp-y   +=  focaltech_spi.o



obj-$(CONFIG_TOUCHSCREEN_FTS)        += fts_tp.o