obj-$(CONFIG_NOTHING_BOOTLOADER_LOG)    += nothing_bootloader_log.o
obj-$(CONFIG_NOTHING_WRITRBACK_KMSG)    += nothing_writeback_kmsg.o


# Add entry point for nothing stability test function
obj-$(CONFIG_NOTHING_STABILITY_TEST)    += test/

obj-$(CONFIG_NOTHING_RESTART_HANDLER) += nothing_restart_handler.o
obj-$(CONFIG_NOTHING_TASK_MEMINFO)    += nothing_task_meminfo.o
